### ISSUE TITLE
Wait for container before executing tests

### ISSUE THREAD

**Issue by fawind** [fawind/docker-test#2]
Wait for container to be up before executing the test command. Possibly using the docker `HEALTHCHECK` option.

**Comment by nstrelow** [comment]
First easy thing we can add, is to define the startup order with depens_on:

- https://docs.docker.com/compose/startup-order/
- https://docs.docker.com/compose/compose-file/#depends_on

Next we can use the wait-for-it script to wait until a specific port is available:
- https://github.com/vishnubob/wait-for-it
Normally this is used, while overriding the startup command of the docker image. And then we would have to know, what the startup command of each container to test is. Maybe there is an alternative.

**Health check**
This is even more sophisticated.
- https://docs.docker.com/compose/compose-file/#healthcheck
- https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y
We would need to specify a command e.g. curl, which finishes with exit code 0, when the server is up.

**Comment by nstrelow** [comment]
Startup order has been established and helping starting mitm-proxy first and everything else afterwards.

Still the test command is executed directly, and will fail when the containers are not ready.

Next step would be to include a check for State.Running as explained here: https://stackoverflow.com/questions/21183088/how-can-i-wait-for-a-docker-container-to-be-up-and-running/33520390#33520390

Preferably define a hardcoded check-if-running command and execute before the test command.

Alternatively we can also try waiting on a host and port.

We can also check if the user has defined a docker health check for the containers to be tested, and check State.Health.Status. If not, we can default to a check-if-running (or wait on host and port).

**Comment by nstrelow** [comment]
Waiting until docker reports the container as running is implemented.

We still need to wait longer until the service is ready to be tested, because the first tests runs before the service is available and fails with:

Error: Timeout of 2000ms exceeded.

Possbilities:

1. We only rely on the user specified --sleep flag
2. We hardcode a small wait time after the container is reported running and hope it works for most cases.
3. We check if the service is reachable via host and port

Additionally we can see if a docker healthcheck has been defined and use it.

**Comment by fawind** [comment]
Waiting for the containers to be up seems to work pretty reliably right now. I'll mark this as closed. If we need further options to delay the execution of tests we can do this in separate issues.
